# Generated by Django 4.1 on 2022-09-21 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_remove_calendar_name_calendar_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevents',
            options={'ordering': ['event_date']},
        ),
        migrations.RemoveField(
            model_name='calendarevents',
            name='events',
        ),
        migrations.AddField(
            model_name='calendarevents',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
