# Generated by Django 4.1 on 2022-09-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_calendarevents_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevents',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Event Date'),
        ),
    ]
