# Generated by Django 4.1 on 2022-09-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_calendarevents_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevents',
            name='event_date',
            field=models.DateField(null=True, verbose_name='Event Date'),
        ),
    ]
